version: '3'

volumes:
  venv:
    driver: 'local'

services:
  django-app:
    build: .
    tty: true
    volumes:
      - .:/app/django_demo
      - venv:/app/django_demo/.venv
    working_dir: /app/django_demo
    ports:
      - 8000:8000
    command: /bin/bash -c "source .venv/bin/activate && python manage.py runserver 0.0.0.0:8000"
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: mysql_demo
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    